server {
    listen @BIND_ADDRESS@:@HTTP_PORT@ default_server;
    server_name _;

    include /opt/liteedge/etc/nginx/security.conf;
    add_header Content-Security-Policy "default-src 'self'; style-src 'self'; img-src 'self' data:; form-action 'self'; frame-ancestors 'none'; base-uri 'none'; object-src 'none'" always;

    location ^~ /.well-known/acme-challenge/ {
        root @DATA_DIR@/acme/challenges;
        auth_basic off;
        try_files $uri =404;
    }

    location /assets/ {
        auth_basic "LiteEdge";
        auth_basic_user_file @DATA_DIR@/auth/.htpasswd;
        alias /opt/liteedge/ui/;
    }

    location / {
        client_max_body_size 32m;
        limit_req zone=liteedge_admin burst=30 nodelay;
        auth_basic "LiteEdge";
        auth_basic_user_file @DATA_DIR@/auth/.htpasswd;
        include /opt/liteedge/etc/nginx/fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /opt/liteedge/cgi/admin.sh;
        fastcgi_param SCRIPT_NAME /admin.sh;
        fastcgi_param PATH_INFO $uri;
        fastcgi_pass unix:@RUN_DIR@/fcgiwrap.sock;
    }
}
