Include @NGINX_DIR@/modsecurity.conf
Include @CRS_DIR@/crs-setup.conf
Include @NGINX_DIR@/modsecurity-pre.conf
Include @CRS_DIR@/rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf
SecAction "id:1000001,phase:1,nolog,pass,setvar:tx.crs_exclusions_wordpress=1"
Include @CRS_DIR@/rules/*.conf
Include @CRS_DIR@/rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf
Include @NGINX_DIR@/modsecurity-overrides.conf
