Include @NGINX_DIR@/modsecurity.conf
Include @CRS_DIR@/crs-setup.conf
Include @NGINX_DIR@/modsecurity-pre.conf
Include @CRS_DIR@/rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf
Include @CRS_DIR@/rules/*.conf
Include @CRS_DIR@/rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf
Include @NGINX_DIR@/modsecurity-overrides.conf
